services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamify-web:latest
    container_name: streamify-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
